_target_: src.models.det_module.BaseDetectionModel

net: rcnn_mobileone
pretrained: True
nms_thresh: 0.5
score_thresh: 0.5

optimizer:
  _target_: "torch.optim.AdamW"
  _partial_: true
  lr: 1e-3
  weight_decay: 5e-4
  betas:
    - 0.9
    - 0.997
  eps: 1e-6

scheduler:
  _target_: "src.lit_modules.schedulers.ChainCyclicLR"
  _partial_: true
  lr_min: 5e-5
  lr_max: 1e-3
  T0: 3
  warmup_steps: 1
  scale_factor: 0.7

# compile model for faster training with pytorch 2.0
compile: false
