_target_: src.models.det_module.BaseDetectionModel

net: fast_base
pretrained: True
cuda: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.95, 0.99]
  eps: 1e-6
  weight_decay: 0.0001
  
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
